language: python
matrix:
  include:
    - python: 3.3
      env: TOXENV=py33-17
    - python: 3.3
      env: TOXENV=py33-18
    - python: 3.4
      env: TOXENV=py34-17
    - python: 3.4
      env: TOXENV=py34-18
    - python: 3.4
      env: TOXENV=py34-19
    - python: 3.5
      env: TOXENV=py35-18
    - python: 3.5
      env: TOXENV=py35-19
    - python: 3.5
      env: TOXENV=py35-110
    - python: 3.5
      env: TOXENV=py35-111
install:
  - pip install "pip<8.0.0"
  - pip install tox
script:
  - tox
